sudo: false
language: node_js
node_js:
  - '10'
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run test
  - npm run eslint-find-rules
after_success:
  - npm run-script coveralls
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
